[package]
name = "killer_bubbles"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra-glm = "0.17.0"
glutin = "0.29.1"
gl = "0.14.0"
rand = "0.8.5"
